language: r
r:
  - release
  - devel

cache: packages
sudo: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'

addons:
  apt:
    packages:
      - jags
